<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Program;

class ProgramSeeder extends Seeder
{
    public function run(): void
    {
        $programs = [
            // Program Bimbel SKD
            [
                'name' => 'Kelas SKD Online Eksklusif',
                'category' => 'Bimbel SKD',
                'badge_text' => '#NGEBUTBELAJAR',
                'badge_color' => 'primary',
                'original_price' => 850000,
                'promo_price' => 500000,
                'duration' => '/15 Sesi',
                'alert_text' => 'KELAS EKSKLUSIF - HANYA 10 ORANG!',
                'alert_color' => 'primary',
                'features' => [
                    'Pengajar Profesional >2 thn',
                    'Rekaman Belajar & Grup Diskusi',
                    'Bebas Konsultasi WhatsApp',
                    '<strong>GRATIS 5x Try Out SKD</strong>',
                    'Monitoring Progress Belajar',
                ],
                'button_text' => 'Daftar Sekarang',
                'button_color' => 'primary',
                'whatsapp_message' => 'Hai Kak, saya sangat tertarik dengan program *Kelas SKD Online Eksklusif* dari Bimbel Speedu. Saya ingin mendaftar dan melanjutkan ke proses pembayaran. Mohon informasinya, terima kasih!',
                'action_type' => 'whatsapp',
                'is_featured' => false,
                'is_active' => true,
                'order' => 1,
            ],
            [
                'name' => 'Kelas SKD Online Prima',
                'category' => 'Bimbel SKD',
                'badge_text' => 'Recommended',
                'badge_color' => 'warning',
                'original_price' => 1500000,
                'promo_price' => 800000,
                'duration' => '/15 Sesi',
                'alert_text' => 'KELAS PRIMA - HANYA 5 ORANG!',
                'alert_color' => 'warning',
                'features' => [
                    'Pengajar Profesional >2 thn',
                    'Rekaman Belajar & Grup Diskusi',
                    'Bebas Konsultasi WhatsApp',
                    '<strong>GRATIS 5x Try Out SKD</strong>',
                    'Monitoring Progress Belajar',
                ],
                'button_text' => 'Ambil Kelas Prima',
                'button_color' => 'warning',
                'whatsapp_message' => 'Hai Kak, saya sangat tertarik dengan program *Kelas SKD Online Prima* dari Bimbel Speedu. Saya ingin mendaftar dan melanjutkan ke proses pembayaran. Mohon informasinya, terima kasih!',
                'action_type' => 'whatsapp',
                'is_featured' => true,
                'is_active' => true,
                'order' => 2,
            ],
            [
                'name' => 'Kelas SKD Privat Offline',
                'category' => 'Bimbel SKD',
                'badge_text' => '#NGEBUTBELAJAR',
                'badge_color' => 'primary',
                'original_price' => 2300000,
                'promo_price' => 1800000,
                'duration' => '/10 Sesi',
                'alert_text' => 'AREA TANGERANG! Guru datang ke rumah.',
                'alert_color' => 'info',
                'features' => [
                    '<strong>Bertemu Langsung</strong> Pengajar',
                    'Materi Super Intensif & Personal',
                    'Bebas Konsultasi WhatsApp',
                    '<strong>GRATIS 5x Try Out SKD</strong>',
                    'Monitoring Progress Belajar',
                ],
                'button_text' => 'Daftar Privat',
                'button_color' => 'primary',
                'whatsapp_message' => 'Hai Kak, saya sangat tertarik dengan program *Kelas SKD Privat Offline* dari Bimbel Speedu. Saya ingin mendaftar dan melanjutkan ke proses pembayaran. Mohon informasinya, terima kasih!',
                'action_type' => 'whatsapp',
                'is_featured' => false,
                'is_active' => true,
                'order' => 3,
            ],

            // Program SKB STMKG
            [
                'name' => 'Kelas Online SKB STMKG Eksklusif',
                'category' => 'Bimbel SKB STMKG',
                'badge_text' => '#NGEBUTBELAJAR',
                'badge_color' => 'primary',
                'original_price' => 800000,
                'promo_price' => 525000,
                'duration' => '/15 Sesi',
                'alert_text' => 'KELAS EKSKLUSIF - HANYA 10 ORANG!',
                'alert_color' => 'primary',
                'features' => [
                    'Pengajar Profesional >2 thn',
                    'Rekaman Belajar & Grup Diskusi',
                    'Bebas Konsultasi WhatsApp',
                    '<strong>GRATIS Try Out SKB</strong>',
                    'Monitoring Progress Belajar',
                ],
                'button_text' => 'Daftar Sekarang',
                'button_color' => 'primary',
                'whatsapp_message' => 'Hai Kak, saya sangat tertarik dengan program *Kelas Online SKB STMKG Eksklusif* dari Bimbel Speedu. Saya ingin mendaftar dan melanjutkan ke proses pembayaran. Mohon informasinya, terima kasih!',
                'action_type' => 'whatsapp',
                'is_featured' => false,
                'is_active' => true,
                'order' => 1,
            ],
            [
                'name' => 'Kelas Online SKB STMKG Prima',
                'category' => 'Bimbel SKB STMKG',
                'badge_text' => 'Recommended',
                'badge_color' => 'warning',
                'original_price' => 1000000,
                'promo_price' => 825000,
                'duration' => '/15 Sesi',
                'alert_text' => 'KELAS PRIMA - HANYA 5 ORANG!',
                'alert_color' => 'warning',
                'features' => [
                    'Pengajar Profesional >2 thn',
                    'Rekaman Belajar & Grup Diskusi',
                    'Bebas Konsultasi WhatsApp',
                    '<strong>GRATIS Try Out SKB</strong>',
                    'Monitoring Progress Belajar',
                ],
                'button_text' => 'Ambil Kelas Prima',
                'button_color' => 'warning',
                'whatsapp_message' => 'Hai Kak, saya sangat tertarik dengan program *Kelas Online SKB STMKG Prima* dari Bimbel Speedu. Saya ingin mendaftar dan melanjutkan ke proses pembayaran. Mohon informasinya, terima kasih!',
                'action_type' => 'whatsapp',
                'is_featured' => true,
                'is_active' => true,
                'order' => 2,
            ],
            [
                'name' => 'Kelas Privat Offline SKB STMKG',
                'category' => 'Bimbel SKB STMKG',
                'badge_text' => '#NGEBUTBELAJAR',
                'badge_color' => 'primary',
                'original_price' => 2500000,
                'promo_price' => 2000000,
                'duration' => '/10 Sesi',
                'alert_text' => 'AREA TANGERANG! Guru datang ke rumah.',
                'alert_color' => 'info',
                'features' => [
                    '<strong>Bertemu Langsung</strong> Pengajar',
                    'Materi Super Intensif & Personal',
                    'Bebas Konsultasi WhatsApp',
                    '<strong>GRATIS Try Out SKB</strong>',
                    'Monitoring Progress Belajar',
                ],
                'button_text' => 'Daftar Privat',
                'button_color' => 'primary',
                'whatsapp_message' => 'Hai Kak, saya sangat tertarik dengan program *Kelas Privat Offline SKB STMKG* dari Bimbel Speedu. Saya ingin mendaftar dan melanjutkan ke proses pembayaran. Mohon informasinya, terima kasih!',
                'action_type' => 'whatsapp',
                'is_featured' => false,
                'is_active' => true,
                'order' => 3,
            ],

            // Paket Try Out
            [
                'name' => '5x Try Out SKD',
                'category' => 'Paket Try Out',
                'badge_text' => '#NGEBUTLATIHAN',
                'badge_color' => 'danger',
                'original_price' => 40000,
                'promo_price' => 30000,
                'duration' => 'Untuk 30 Pendaftar Pertama',
                'alert_text' => null,
                'alert_color' => 'primary',
                'features' => [
                    'Bisa dikerjakan kapanpun',
                    'Soal FR terupdate',
                    'Pembahasan dapat diunduh',
                    'Join Grup Diskusi',
                    'Perankingan Peserta',
                ],
                'button_text' => 'Daftar Try Out',
                'button_color' => 'outline-primary',
                'whatsapp_message' => null,
                'action_type' => 'register',
                'is_featured' => false,
                'is_active' => true,
                'order' => 1,
            ],
            [
                'name' => '10x Try Out SKD',
                'category' => 'Paket Try Out',
                'badge_text' => '#NGEBUTLATIHAN',
                'badge_color' => 'danger',
                'original_price' => 80000,
                'promo_price' => 50000,
                'duration' => 'Untuk 30 Pendaftar Pertama',
                'alert_text' => null,
                'alert_color' => 'primary',
                'features' => [
                    'Bisa dikerjakan kapanpun',
                    'Soal FR terupdate',
                    'Pembahasan dapat diunduh',
                    'Join Grup Diskusi',
                    'Perankingan Peserta',
                ],
                'button_text' => 'Daftar Try Out',
                'button_color' => 'warning',
                'whatsapp_message' => null,
                'action_type' => 'register',
                'is_featured' => true,
                'is_active' => true,
                'order' => 2,
            ],
            [
                'name' => '3x Try Out SKB STMKG',
                'category' => 'Paket Try Out',
                'badge_text' => '#NGEBUTLATIHAN',
                'badge_color' => 'danger',
                'original_price' => 45000,
                'promo_price' => 30000,
                'duration' => 'Untuk 30 Pendaftar Pertama',
                'alert_text' => null,
                'alert_color' => 'primary',
                'features' => [
                    'Mencakup MTK, Fisika, B. Inggris',
                    'Soal FR terupdate',
                    'Pembahasan dapat diunduh',
                    'Join Grup Diskusi',
                    'Perankingan Peserta',
                ],
                'button_text' => 'Daftar Try Out',
                'button_color' => 'outline-primary',
                'whatsapp_message' => null,
                'action_type' => 'register',
                'is_featured' => false,
                'is_active' => true,
                'order' => 3,
            ],
        ];

        foreach ($programs as $program) {
            Program::create($program);
        }
    }
}
